# Generated by Django 5.2.4 on 2025-08-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='', verbose_name='blog_image')),
                ('title', models.TextField(verbose_name='blog_title')),
                ('short_description', models.TextField(verbose_name='blog_short_des')),
                ('long_description', models.TextField(verbose_name='blog_long_des')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
    ]
